sudo: required

language: ruby

services:
  - docker

before_install:
  - echo -e "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_PASSWORD\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_PASSWORD" >> ~/.netrc


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    curl https://cli-assets.heroku.com/install-ubuntu.sh | sh;
    docker build -t goal-backend .;
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_PASSWORD" registry.heroku.com;
    docker tag goal-backend registry.heroku.com/goal-backend/web;
    docker push registry.heroku.com/goal-backend/web;
    heroku container:release web -a goal-backend;
    fi
