version: '3'
services:
  service: &default
    image: ghrehh/goal-backend
    build: .
    entrypoint: dockerize -wait tcp://postgres:5432
    command: bundle exec rails s
    volumes:
      - ./app:/usr/src/goals-backend/app
      - ./config:/usr/src/goals-backend/config
      - ./lib:/usr/src/goals-backend/lib
      - ./spec:/usr/src/goals-backend/spec
    environment:
      - DATABASE_URL=postgresql://postgres:@postgres/postgres?sslmode=disable
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres: &postgres
    image: postgres:9.4-alpine
