version: '3'
services:
  service: &default
    image: ghrehh/goal-backend
    build: .
    entrypoint: dockerize -wait tcp://postgres:5432
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./app:/usr/src/score-api/app
      - ./lib:/usr/src/score-api/lib
      - ./db:/usr/src/score-api/db
      - ./spec:/usr/src/score-api/spec
      - ./config:/usr/src/score-api/config
    environment:
      - DATABASE_URL=postgresql://postgres:@postgres/postgres?sslmode=disable
    ports:
      - "0.0.0.0:3001:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres: &postgres
    image: postgres:9.4-alpine
